"""empty message

Revision ID: 248d2f0b983c
Revises: e7795937487b
Create Date: 2024-05-11 23:46:26.751910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248d2f0b983c'
down_revision = 'e7795937487b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('quantidade', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'quantidade')
    # ### end Alembic commands ###
