"""empty message

Revision ID: 87f1640694a1
Revises: 9c9cd9d9d587
Create Date: 2024-05-12 00:49:42.846145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f1640694a1'
down_revision = '9c9cd9d9d587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario_produto', sa.Column('quantidade_produto', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario_produto', 'quantidade_produto')
    # ### end Alembic commands ###
